name: Verrify
title: Verrify
email: hello@verrify.com

description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://verrify.com" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: dfct_
github_username:  verrify


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:title/

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock


navigation:
  - label: Example Page
    url: /technology
  - label: Example Page
    url: /docs
  - label: Example Page
    url: /contact


navigation-footer:
#  - label: Company
#    url: /company
  - label: Blog
    url: https://blog.verrify.com
#  - label: Privacy
#    url: /privacy
#  - label: Terms
#    url: /terms
  - label: Contact
#    url: /contact
    url: mailto:hello@verrify.com